yarky/blog/urls.py
# coding: utf-8

from django.conf.urls import *
from blog.views import BlogView, BlogEntryView, BlogCalendarView

urlpatterns = patterns('admin.views',
    url(r'^$', BlogView.as_view(), name="list"),
    url(r'^get_calendar/$', BlogCalendarView.as_view(), name="get-calendar"),
    url(r'^(?P<slug>[a-z0-9\-\_]+)/$', BlogEntryView.as_view(), name="entry"),
)

yarky/content/models.py
# coding: utf-8
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.core.urlresolvers import reverse
from django.core.validators import BaseValidator
from django.db import models
from translation.models import TranslationGetterMixin, TranslationModel
from yarky.helpers import HTMLField


class ImageHeightValidator(BaseValidator):

    def __init__(self, height):
        super().__init__(height)
        self.height = height

    def __call__(self, image):
        if not image:
            return

        _, height = get_image_dimensions(image)

        if not self.height == height:
            raise ValidationError(
                u"Высота картинки должна быть {0}".format(self.height)
            )


class SlideGroup(models.Model):

    key = models.SlugField(max_length=32, verbose_name=u"Ключ группы")

    class Meta:
        verbose_name = u"Группа слайдов"
        verbose_name_plural = u"Группы слайдов"

    def __str__(self):
        return self.key


class Slide(TranslationGetterMixin, models.Model):

    title = models.CharField(max_length=150,
                             verbose_name=u"Системное название",
                             editable=False, default="Слайд")
    group = models.ForeignKey(SlideGroup, related_name="slides")
    image = models.ImageField(upload_to="slides/",
                              verbose_name=u"Картинка",
                              validators=[ImageHeightValidator(height=565)])
    colors = (
        ("darkorange", "Оранжевый"),
        ("brightgreen", "Зеленый"),
        ("acidpink", "Кислотно-розовый"),
        ("pink", "Розовый"),
        ("aqua", "Морской"),
        ("cyan", "Голубой"),
        ("gray", "Серый"),
        ("black", "Черный"),
        ("white", "Белый"),
    )
    background = models.CharField(max_length=32, choices=colors,
                                  verbose_name=u"Цвет фона")
    title_color = models.CharField(max_length=32, choices=colors,
                                   verbose_name=u"Цвет заголовка",
                                   default="black")
    subtitle_color = models.CharField(max_length=32, choices=colors,
                                      verbose_name=u"Цвет текста",
                                      default="white")

    published = models.BooleanField(default=True, verbose_name=u"Опубликовано")
    position = models.PositiveSmallIntegerField(default=0,
                                                verbose_name=u"Позиция",
                                                editable=False)

    class Meta:
        verbose_name = u"Слайд"
        verbose_name_plural = u"Слайды"
        ordering = ["position"]

    def __str__(self):
        return self.title


class SlideTranslation(TranslationModel):

    base_model = Slide

    title = models.CharField(max_length=128, verbose_name=u"Заголовок",
                             blank=True, default="")
    subtitle = HTMLField(verbose_name=u"Подзаголовок", blank=True,
                         default="")

    class Meta:
        verbose_name = u"Слайд"
        verbose_name_plural = u"Слайды"
        ordering = ["base__position"]

    def __str__(self):
        return self.title


class Page(models.Model, TranslationGetterMixin):

    title = models.CharField(max_length=150, verbose_name=u"Системное название",
                             unique=True, editable=False, default=u"Статья")
    slug = models.SlugField(max_length=150, verbose_name=u"Код для URL",
                            unique=True, db_index=True)

    inline = models.BooleanField(default=False, verbose_name="Скрытая")
    updated = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        verbose_name = u"Статья"
        verbose_name_plural = u"Статьи"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article", args=[self.slug])


class PageTranslation(TranslationModel):

    base_model = Page

    title = models.CharField(max_length=150, verbose_name=u"Заголовок")
    content = HTMLField(verbose_name=u"Содержание", blank=True, default="")

    class Meta:
        verbose_name = u"Статья"
        verbose_name_plural = u"Статьи"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return self.base.get_absolute_url()


class Reservation(models.Model):
    date_in = models.DateField()
    date_out = models.DateField()
    guests = models.PositiveSmallIntegerField()

    breakfasts = (
        ('0', 'Не включены'),
        ('1', 'Включены')
    )
    breakfast = models.CharField(max_length=1, choices=breakfasts)
    room_type = models.ForeignKey("Room")
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    phone = models.CharField(max_length=64)
    email = models.EmailField()
    comment = models.TextField(blank=True, null=True)

    def get_price(self):
        return self.room_type.price

    def total_cost(self):
        return (self.get_price()+int(self.breakfast)*180)*self.guests


class TerritoryInfo(TranslationGetterMixin, models.Model):

    title = models.CharField(max_length=128,
                             verbose_name=u"Системное название",
                             editable=False)
    territories = (
        ("green", "Зеленая"),
        ("red", "Красная"),
        ("blue", "Синяя"),
        ("yellow", "Желтая"),
    )
    territory = models.CharField(max_length=10, verbose_name=u"Территория",
                                 choices=territories)
    collapsable = models.BooleanField(default=True,
                                      verbose_name=u"Сворачивается")
    position = models.PositiveSmallIntegerField(default=0,
                                                verbose_name=u"Позиция",
                                                editable=False)
    published = models.BooleanField(verbose_name=u"Опубликовано", default=True)

    class Meta:
        verbose_name = u"Территория"
        verbose_name_plural = u"Территории"
        ordering = ["territory", "position"]

    def __str__(self):
        return self.title


class TerritoryInfoTranslation(TranslationModel):

    base_model = TerritoryInfo

    title = models.CharField(max_length=128, verbose_name=u"Заголовок")
    text = HTMLField(verbose_name=u"Описание")

    class Meta:
        verbose_name = u"Территория"
        verbose_name_plural = u"Территории"
        ordering = ["base__territory", "base__position"]

    def __str__(self):
        return self.title



class Room(models.Model, TranslationGetterMixin):

    title = models.CharField(max_length=150, verbose_name=u"Системное название",
                             editable=False, default="Номер")

    places = models.PositiveSmallIntegerField(verbose_name=u"Количество мест")
    price = models.PositiveIntegerField(verbose_name=u"Цена за ночь")

    image = models.ImageField(upload_to="rooms/", verbose_name=u"Фото")

    published = models.BooleanField(default=True, verbose_name=u"Опубликовано")
    position = models.PositiveSmallIntegerField(default=0,
                                                verbose_name=u"Позиция",
                                                editable=False)

    class Meta:
        verbose_name = u"Номер"
        verbose_name_plural = u"Номера"
        ordering = ["position"]

    def __str__(self):
        return self.title


class RoomTranslation(TranslationModel):

    base_model = Room

    title = models.CharField(max_length=150, verbose_name=u"Заголовок")
    short_title = models.CharField(max_length=150,
                                   verbose_name=u"Короткий заголовок")
    description = HTMLField(verbose_name=u"Описание")

    class Meta:
        verbose_name = u"Номер"
        verbose_name_plural = u"Номера"
        ordering = ["base__position"]

    def __str__(self):
        return self.title


class SimpleImage(models.Model):
    image = models.ImageField(upload_to="images/")

templates/include/analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52713258-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>

templates/include/footer.html
<footer>
    <div class="container">
        <div class="contacts">
            <a href="tel:{{ setting("contact-phone") }}">{{ setting("contact-phone") }}</a>,

            <a href="mailto: welcome@yarkyhostel.com">welcome@yarkyhostel.com</a>

            {% include "include/social_links.html" %}
        </div>
    </div>
</footer>

templates/include/head.html
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">

    <link rel="icon" href="{{ static("images/favicon-16x16.png") }}" sizes="16x16" type="image/png">
    <link rel="icon" href="{{ static("images/favicon-32x32.png") }}" sizes="32x32" type="image/png">
    <link rel="icon" href="{{ static("images/favicon-96x96.png") }}" sizes="96x96" type="image/png">
    <link rel="icon" href="{{ static("images/favicon.ico") }}" sizes="16x16 32x32 48x48" type="image/vnd.microsoft.icon">

    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,700&amp;subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ static("styles/main.css") }}" />
    {% if windows_user(request) %}<link rel="stylesheet" href="{{ static("styles/overrides.css") }}" />{% endif %}

    <script type="text/javascript">var CURRENT_LANG = '{{ current_lang() }}';</script>
    <script src="{{ static("js/main.js") }}" type="text/javascript"></script>
    <script src="{{ static("javascript/lib/socialshare.min.js") }}" type="text/javascript"></script>

    <script type="text/javascript">
        (function() {
            var path = '//easy.myfonts.net/v2/js?sid=214511(font-family=Harmonia+Sans+Pro+Cyrillic+Light)&sid=214513(font-family=Harmonia+Sans+Pro+Cyrillic+Regular)&sid=214517(font-family=Harmonia+Sans+Pro+Cyrillic+Bold)&sid=214519(font-family=Harmonia+Sans+Pro+Cyrillic+Black)&key=oW2mQoRNIV',
                protocol = ('https:' == document.location.protocol ? 'https:' : 'http:'),
                trial = document.createElement('script');
            trial.type = 'text/javascript';
            trial.async = true;
            trial.src = protocol + path;
            var head = document.getElementsByTagName("head")[0];
            head.appendChild(trial);
        })();
    </script>

templates/include/language_switcher.html
<div class="lang-switch pull-left">
{#    {% for lang in get_languages() %}#}
{#        <div class="lang{% if lang.code == current_lang() %} active{% endif %}">#}
{#            {% if lang.code == current_lang() %}#}
{#                {{ lang.title|lower }}#}
{#            {% else %}#}
{#                <a class="{{ lang.code }}" href="{{ translate_path(path, lang.code) }}">#}
{#                    {{ lang.title|lower }}#}
{#                </a>#}
{#            {% endif %}#}
{#        </div>#}
{#    {% endfor %}#}
</div>

templates/include/reservation_result.html
<h3 class="title">Уважаемый, {{ reservation.first_name }} {{ reservation.last_name }}, вы отправили заявку на бронирование</h3>
<div class="result-info col-left pull-left">
    <div class="result-info-row">
        <div class="subtitle">Дата заезда</div>
        <div class="value">{{ reservation.date_in|date("d.m.Y") }}</div>
    </div>
    <div class="result-info-row">
        <div class="subtitle">Дата выезда</div>
        <div class="value">{{ reservation.date_out|date("d.m.Y") }}</div>
    </div>
    <div class="result-info-row">
        <div class="subtitle">Количество гостей</div>
        <div class="value">{{ reservation.guests }}</div>
    </div>
    <div class="result-info-row">
        <div class="subtitle">Тип номера</div>
        <div class="value">{{ reservation.room_type.get_local_title }}</div>
    </div>
    <div class="result-info-row">
        <div class="subtitle">Email</div>
        <div class="value">{{ reservation.email }}</div>
    </div>
    <div class="result-info-row">
        <div class="subtitle">Телефон</div>
        <div class="value">{{ reservation.phone }}</div>
    </div>
</div>
<div class="result-info col-right">
    <div class="result-info-row">
        <div class="subtitle">Завтраки</div>
        <div class="value">{{ reservation.get_breakfast_display() }}</div>
    </div>
    <div class="result-info-row">
        <div class="subtitle">Особые пожелания</div>
        <div class="value">{{ reservation.comment }}</div>
    </div>
    <div class="result-info-row result-sum">
        <nobr><strong>Общая стоимость</strong></nobr>
        {{ reservation.total_cost() }} Р.
    </div>
</div>
<div class="clearfix"></div>
<div class="result-info-text">
    Заявка будет принята к рассмотрению.<br/>На вашу электронную почту будет выслано финальное подтверждение. Бронирование считается негарантированным до подтверждения заявки  администрацией отеля. Если в ближайшее время подтверждение не будет получено, свяжитесь с отелем напрямую по адресу <a href="mailto:welcome@yarkyhostel.com">welcome@yarkyhostel.com</a>
</div>
<div class="result-info">
    <a href="#" class="button-success close-reservation">Закрыть окно</a>
</div>

templates/include/rooms_select.html
<select name="room_type" class="room_type wide">
    {% for room in rooms %}
        <option value="{{ room.base.id }}" data-guests-max="{{ room.base.places }}" data-price="{{ room.base.price }}">{{ room.short_title }}</option>
    {% endfor %}
</select>

templates/include/rooms_widget.html
<div class="room-list">
    {% for room in rooms %}
        <div class="room-item room-item-{{ room.base.id }}">
            <div class="room">
                <div class="room-img">
                    <img src="{{ thumbnail(room.base.image, "200x135", crop="center").url }}" alt=""  />
                </div>
                <div class="room-title">{{ room.title }}</div>
                <div class="room-description">
                    {{ room.description|safe }}
                </div>
                <div class="room-price">
                    {{ room.base.price }} P
                    <strong>за ночь</strong>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

templates/include/slide.html
    <div class="carousel-item" data-bgrcolor="{{ slide.base.background }}" data-title_color="{{ slide.base.title_color }}" data-subtitle_color="{{ slide.base.subtitle_color }}">
        <div class="container">
            <div class="item-description">
                <h2 class="index-title {{ slide.base.title_color }}">{{ slide.title|linebreaksbr|safe }}</h2>
                <div class="item-text {{ slide.base.subtitle_color }}">{{ slide.subtitle|safe }}</div>
            </div>
            <div class="item-img" style="background-image: url({{ slide.base.image.url }})"></div>
        </div>
    </div>

templates/include/social_links.html
<ul class="social-networks">
    <li>
        <a class="fb" href="http://fb.com/yarky">
            <div class="icon icon--ei-sc-facebook icon--s"><svg class="icon__cnt"><use xlink:href="#ei-sc-facebook-icon" /></svg></div>
        </a>
    </li>
    <li>
        <a class="vk" href="http://vk.com/yarkyhostel">
            <div class="icon icon--ei-sc-vk icon--s"><svg class="icon__cnt"><use xlink:href="#ei-sc-vk-icon" /></svg></div>
        </a>
    </li>
    <li>
        <a class="ig" href="http://instagram.com/yarkyspace">
            <div class="icon icon--ei-sc-instagram icon--s"><svg class="icon__cnt"><use xlink:href="#ei-sc-instagram-icon" /></svg></div>
        </a>
    </li>
</ul>

templates/include/social_share.html
<ul class="social-networks">
    <li>
        <a class="s-facebook social-icon" target="_blank">
            <div class="icon icon--ei-sc-facebook icon--s"><svg class="icon__cnt"><use xlink:href="#ei-sc-facebook-icon" /></svg></div>
        </a>
    </li>
    <li>
        <a class="s-vk social-icon" target="_blank">
            <div class="icon icon--ei-sc-vk icon--s"><svg class="icon__cnt"><use xlink:href="#ei-sc-vk-icon" /></svg></div>
        </a>
    </li>
</ul>

templates/include/territory.html
<div class="places pull-right hidden">
    <div class="places-close pull-right"></div>
    {% for group in territory|groupby('base.territory') %}
        {% if group.list|length %}
            <div class="places-content {{ group.grouper }} hidden scrollable">
                <ul class="places-list">
                {% for info in group.list %}
                    <li>
                        {% if info.base.collapsable %}
                            <h3><a href="#">{{ info.title }}</a></h3>
                        {% else %}
                            <strong>{{ info.title }}</strong>
                        {% endif %}
                        {{ info.text|safe }}
                    </li>
                {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endfor %}
    <div class="clearfix"></div>
</div>